title:
author: ynwarcs
github: https://github.com/ynwarcs
reddit: https//reddit.com/u/goodbyeselene
email: ynwarcs@proton.me
mstdn: https://infosec.exchange/@ynwarcs
description: >
favicon: "./favicon.ico" # set the favicon of the site
permalink: /:title

show_excerpts: true # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

# Build settings
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
